site_name: Keybot 5716
copyright: © Copyright 2025, Keybot 5716
site_author: Equipo de programación / Fundador de página (Lider de programación 2021 - 2023 UwU)
theme:
  name: readthedocs
  logo: logo.png